image: python:3.11

stages:
  - lint
  - test

flake8:
  stage: lint
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install -r requirements/test.txt
    - flake8 --verbose

black:
  stage: lint
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check --verbose -- .

check_requirements:
  stage: lint
  script:
    - pip install sort-requirements
    - sort-requirements --check requirements/dev.txt requirements/prod.txt requirements/test.txt

test:
  stage: test
  rules:
    - when: never
  script:
    - pip install -r requirements/test.txt
    - cd lyceum
    - python manage.py test