# Generated by Django 5.2.10 on 2026-04-11 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "status",
                    models.CharField(
                        default="lobby",
                        help_text="жизненный цикл: lobby, active, finished",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        default="waiting",
                        help_text="waiting, night, day, voting",
                        max_length=20,
                        verbose_name="фаза",
                    ),
                ),
                (
                    "round",
                    models.PositiveIntegerField(
                        default=0, verbose_name="раунд"
                    ),
                ),
                (
                    "seq",
                    models.BigIntegerField(
                        default=0, verbose_name="счётчик событий"
                    ),
                ),
                (
                    "balance_config",
                    models.JSONField(
                        default=dict, verbose_name="конфиг баланса"
                    ),
                ),
                (
                    "analytics_language",
                    models.CharField(
                        default="ru",
                        max_length=10,
                        verbose_name="язык аналитики",
                    ),
                ),
                (
                    "investigation_pct",
                    models.FloatField(
                        default=0.0, verbose_name="шкала расследования"
                    ),
                ),
                (
                    "panic_pct",
                    models.FloatField(
                        default=0.0, verbose_name="шкала паники"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="создана"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="обновлена"
                    ),
                ),
            ],
            options={
                "verbose_name": "игровая сессия",
                "verbose_name_plural": "игровые сессии",
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="роль"
                    ),
                ),
                (
                    "is_alive",
                    models.BooleanField(default=True, verbose_name="жив"),
                ),
                (
                    "ready",
                    models.BooleanField(default=False, verbose_name="готов"),
                ),
                (
                    "traits",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="черты"
                    ),
                ),
                (
                    "ip_balance",
                    models.IntegerField(
                        default=0, verbose_name="очки внимания"
                    ),
                ),
                (
                    "inventory",
                    models.JSONField(
                        blank=True, default=list, verbose_name="инвентарь"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="game.gamesession",
                        verbose_name="сессия",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "участник",
                "verbose_name_plural": "участники",
                "unique_together": {("session", "user")},
            },
        ),
    ]
