# Generated by Django 5.2.10 on 2026-04-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="ends_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="окончание текущей фазы"
            ),
        ),
        migrations.AlterField(
            model_name="gamesession",
            name="phase",
            field=models.CharField(
                default="lobby",
                help_text="lobby, preparation, activity, night, analytics, court, finished",
                max_length=20,
                verbose_name="фаза",
            ),
        ),
    ]
