# Generated by Django 5.2 on 2026-04-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_domain_models"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="evidence",
            new_name="game_eviden_session_b9b03e_idx",
            old_name="game_eviden_session_e87ad4_idx",
        ),
        migrations.RenameIndex(
            model_name="gamelog",
            new_name="game_gamelo_session_81d0af_idx",
            old_name="game_gamelo_session_6f21a0_idx",
        ),
        migrations.RenameIndex(
            model_name="traitsnapshot",
            new_name="game_traits_partici_20d83d_idx",
            old_name="game_traits_particip_8a3b9f_idx",
        ),
        migrations.RenameIndex(
            model_name="voterecord",
            new_name="game_votere_session_285fb2_idx",
            old_name="game_votere_session_1c2d8e_idx",
        ),
        migrations.AddField(
            model_name="gamesession",
            name="win_summary",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="итог победы"
            ),
        ),
    ]
