# Generated by Django 5.2 on 2026-04-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_win_summary"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pollresult",
            unique_together={("session", "round", "voter")},
        ),
    ]
