# Generated by Django 5.2 on 2026-04-19 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_poll_unique_and_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="doctor_last_healed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="doctor_last_heal_sessions",
                to="game.participant",
                verbose_name="последний игрок, которого лечил доктор",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="sheriff_checks",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="результаты проверок комиссара",
            ),
        ),
        migrations.AlterField(
            model_name="gamesession",
            name="phase",
            field=models.CharField(
                default="lobby",
                help_text="lobby, day_discussion, day_vote, night, finished (классика)",
                max_length=20,
                verbose_name="фаза",
            ),
        ),
        migrations.CreateModel(
            name="PlayerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hints_enabled",
                    models.BooleanField(
                        default=True, verbose_name="показывать подсказки"
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        default="ru",
                        max_length=2,
                        verbose_name="язык подсказок",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "профиль игрока",
                "verbose_name_plural": "профили игроков",
            },
        ),
    ]
