# Generated by Django 5.2

import django.core.validators
import django.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_classic_mafia_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="max_players",
            field=django.db.models.PositiveSmallIntegerField(
                default=7,
                help_text="размер лобби до старта партии (классика)",
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(15),
                ],
                verbose_name="игроков за столом",
            ),
        ),
    ]
