# Generated by Django 5.2 on 2026-04-19 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_gamesession_max_players"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="max_players",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text="размер лобби до старта партии (классика)",
                validators=[
                    django.core.validators.MinValueValidator(4),
                    django.core.validators.MaxValueValidator(15),
                ],
                verbose_name="игроков за столом",
            ),
        ),
    ]
