# Generated by Django 5.2.10 on 2026-04-20 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_gamesession_min_players_4"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="max_players",
            field=models.PositiveSmallIntegerField(
                default=4,
                help_text="размер лобби до старта партии (классика)",
                validators=[
                    django.core.validators.MinValueValidator(4),
                    django.core.validators.MaxValueValidator(15),
                ],
                verbose_name="игроков за столом",
            ),
        ),
    ]
