# Generated by Django 5.2.10 on 2026-04-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_alter_gamesession_max_players"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="traits",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="приметы игрока"
            ),
        ),
    ]
