# Generated by Django 5.2.10 on 2026-04-21 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0010_alter_participant_traits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidence",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidences",
                to="game.gamesession",
            ),
        ),
    ]
