# Generated by Django 5.2.10 on 2026-04-21 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0011_alter_evidence_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidences",
                to="game.participant",
                verbose_name="владелец улики",
            ),
        ),
    ]
